# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_image', '0003_auto_20170621_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTeg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_image.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='imageteg',
            name='teg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_image.Tegs'),
        ),
    ]
