# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_image', '0004_auto_20170622_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageTeg',
            new_name='ImageTag',
        ),
        migrations.RenameModel(
            old_name='Tegs',
            new_name='Tags',
        ),
        migrations.RenameField(
            model_name='imagetag',
            old_name='teg',
            new_name='tag',
        ),
    ]
