# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_image', '0006_auto_20170622_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(max_length=30, verbose_name='Короткое описание'),
        ),
    ]
